version: '3'
services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ${SITES_VOLUME}:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/ssl:/etc/nginx/ssl
      - ./data/logs/nginx:/var/log/nginx
    environment:
      - TZ=${TIMEZONE}

  php7.2:
    build: php/7.2
    volumes:
      - ${SITES_VOLUME}:/var/www/
      - ./data/logs/php:/var/log/php-fpm
      - ./php/7.2/config.ini:/usr/local/etc/php/conf.d/app-config.ini
    user: www-data
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}

  php7.3:
    build: php/7.3
    volumes:
      - ${SITES_VOLUME}:/var/www/
      - ./data/logs/php:/var/log/php-fpm
      - ./php/7.3/config.ini:/usr/local/etc/php/conf.d/app-config.ini
    user: www-data
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}

  db:
    image: mysql:5.7
    volumes:
      - ./data/logs/db:/var/log/mysql
      - ./data/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/default.cnf
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}

  pgdb:
    image: postgres:alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TIMEZONE}

  pma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /sessions
    ports:
      - ${PMA_LOCAL_PORT}:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}

  memcached:
    image: memcached:alpine
    expose:
    - 11211
    command: memcached -m 1024m -I 4m

  redis:
    image: redis:3-alpine
    volumes:
    - ./data/redis:/data
    ports:
    - 6379:6379

  php-redis-admin:
    image: faktiva/php-redis-admin
    container_name: pra
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 89:80
    depends_on:
      - redis

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/mongo_config:/data/configdb

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - ${RABBITMQ_NODE_HOST_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672
      - ${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    hostname: laradock-rabbitmq
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  mailhog:
    image: mailhog/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./data/mailhog/volume:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"